// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const SET_RANKING_USERS = 'SET_RANKING_USERS';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_PROJECTS = 'SET_PROJECTS';
export const SET_DEFAULT_PROJECTS = 'SET_DEFAULT_PROJECTS';
export const SET_PROJECT = 'SET_PROJECT';
export const LIKE_PROJECT = 'LIKE_PROJECT';
export const UNLIKE_PROJECT = 'UNLIKE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const POST_PROJECT = 'POST_PROJECT';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
//Trash reducer types

export const SET_STATS_TRASH = 'SET_STATS_TRASH';
export const SET_TOTALS_TRASH = 'SET_TOTALS_TRASH';
export const SET_TRASH_HISTORY = 'SET_TRASH_HISTORY';
export const SET_USER_RECYCLING = 'SET_USER_RECYCLING';